branches:
  only:
    - master
    
install:
  - set QTDIR=C:\Qt\5.8\mingw53_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;
  
build_script:
  - qmake timer.pro
  - mingw32-make
  
after_build:
  - rm release/*.o

artifacts:
  - path: release
    type: zip
